[package]
name = "starry-vm"
version = "0.2.0"
edition = "2024"
authors = ["朝倉水希 <asakuramizu111@gmail.com>", "Mivik <mivikq@gmail.com>"]
description = "Virtual memory management library for Starry OS"
keywords = ["starry-os"]
license = "Apache-2.0"
repository = "https://github.com/Starry-OS/starry-vm"

[features]
default = ["alloc"]
alloc = []

[dependencies]
axerrno = { workspace = true }
bytemuck = { version = "1.24", features = [
    "align_offset",
    "const_zeroed",
    "zeroable_maybe_uninit",
] }
extern-trait = "0.2"

[dev-dependencies]
bytemuck = { version = "1.24", features = ["derive"] }

[package.metadata.docs.rs]
all-features = true
