# Architecture identifier.
arch = "x86_64"                 # str
# Platform identifier.
platform = "x86-csv"             # str
# Platform Package.
package = "axplat-x86-csv"       # str

#
# Platform configs
#
[plat]
# Maximum number of CPUs. For platforms that do not support runtime CPU number
# detection, it's also the number of CPUs to boot.
cpu-num = 1                     # uint
max-cpu-num = 1                 # uint
# Base address of the whole physical memory.
phys-memory-base = 0            # uint
# Size of the whole physical memory. (128M)
phys-memory-size = 0x800_0000   # uint
# Base physical address of the kernel image.
kernel-base-paddr = 0x0150_0000   # uint
# Base virtual address of the kernel image.
kernel-base-vaddr = "0xffff_8000_0150_0000"     # uint
# Linear mapping offset, for quick conversions between physical and virtual
# addresses.
phys-virt-offset = "0xffff_8000_0000_0000"      # uint
# Offset of bus address and phys address. some boards, the bus address is
# different from the physical address.
phys-bus-offset = 0                             # uint
# Kernel address space base.
kernel-aspace-base = "0xffff_8000_0000_0000"    # uint
# Kernel address space size.
kernel-aspace-size = "0x0000_7fff_ffff_f000"    # uint
# Stack size on bootstrapping. (256K)
boot-stack-size = 0x40000                       # uint
# SEV C-bit position (0 to disable SEV encryption bit).
sev-cbit-pos = 47                               # uint
# VirtIO shared memory pool base address for AMD SEV (unencrypted region).
shared-mem-base = 0x0100_0000                   # uint
# VirtIO shared memory pool size.
shared-mem-size = 0x0020_0000                   # uint

#
# Device specifications
#
[devices]
# MMIO ranges with format (`base_paddr`, `size`).
mmio-ranges = [
    [0x8000_0000, 0x3000_0000], # PCI MMIO window (lower)
    [0xb000_0000, 0x1000_0000], # PCI config space
    [0xc000_0000, 0x3e00_0000], # PCI MMIO window (upper)
    [0x8000_0000_0, 0x1000_0000], # PCI MMIO window (64-bit)
    [0xfec0_0000, 0x1000],      # IO APIC
    [0xfed0_0000, 0x1000],      # HPET
    [0xfee0_0000, 0x1000],      # Local APIC
]                               # [(uint, uint)]
# VirtIO MMIO ranges with format (`base_paddr`, `size`).
virtio-mmio-ranges = []         # [(uint, uint)]
# Base physical address of the PCIe ECAM space (should read from ACPI 'MCFG' table).
pci-ecam-base = 0xb000_0000     # uint
# End PCI bus number.
pci-bus-end = 0xff              # uint
# PCI device memory ranges (not used on x86).
pci-ranges = []                 # [(uint, uint)]

# Timer interrupt frequency in Hz. (4.0GHz)
timer-frequency = 4_000_000_000     # uint
# Timer interrupt num.
timer-irq = 0xf0                    # uint
# IPI interrupt num
ipi-irq = 0xf3                      # uint
