[package]
name = "strace"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
homepage = ""
repository = ""

[dependencies]
libc = "0.2"
syscall-numbers = "4.0.2"

[[bin]]
name = "strace"
path = "src/main.rs"

[workspace]
