[package]
name = "axfs-ng-vfs"
version = "0.1.0"
edition = "2024"
authors = ["Mivik <mivikq@gmail.com>", "朝倉水希 <asakuramizu111@gmail.com>"]
description = "Virtual filesystem layer for ArceOS"
keywords = ["vfs", "filesystem", "axfs-ng", "arceos"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Starry-OS/axfs-ng-vfs"

[dependencies]
axerrno = { workspace = true}
axpoll = { workspace = true }
bitflags = "2.10"
cfg-if = "1"
hashbrown = "0.15"
inherit-methods-macro = "0.1"
log = "0.4"
smallvec = "1.15"
spin = { version = "0.10", default-features = false, features = ["mutex"] }
