[package]
name = "starry-process"
version = "0.2.0"
edition = "2024"
authors = ["朝倉水希 <asakuramizu111@gmail.com>"]
description = "Process management for Starry OS"
keywords = ["starry-os"]
license = "Apache-2.0"
repository = "https://github.com/Starry-OS/starry-process"

[dependencies]
kspin = "0.1"
lazyinit = "0.2.1"
weak-map = "0.1"

[dev-dependencies]
ctor = "0.4.1"
kspin = { version = "0.1", features = ["smp"] }
